version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."      
      - pip install aws-sam-cli      
      - pip install pytest pytest-mock
      - cd cicd-pipelines
  pre_build:
    commands:
      - echo "Running sam build..."
      - sam build
  build:
    commands:
      - echo "Packing sam template..."
      - sam package --output-template-file packaged.yaml --s3-bucket andres-ocampo-bucket
      - echo "Running tests..."
      - pytest tests/unit
artifacts:
  files:
     - cicd-pipelines/packaged.yaml