version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t ./package
      - pip install aws-sam-cli      
      - cd cicd-pipelines
  pre_build:
    commands:
      - echo "Running sam build..."
      - sam build
  build:
    commands:
      - echo "Running our build commands..."